[[pages]]
path = "pages/Sandbox.py"
name = "Sandbox"

[[pages]]
path = "pages/Sandbox_instructions.py"
name = "Sandbox Instructions"

[[pages]]
path = "pages/Practice.py"
name = "Mutations Practice"

[[pages]]
path = "pages/Transcription.py"
name = "Transcription"

[[pages]]
path = "pages/Translation.py"
name = "Translation"

[[pages]]
path = "pages/MutationQuiz.py"
name = "Identify Mutations"
